apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: data
spec:
  type: NodePort  
  ports:
  - port: 9000
    targetPort: 9000
    name: minio
  - port: 9090
    targetPort: 9090
    name: console
  selector:
    app: minio