apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command: ["/bin/bash", "-c"]
        args: ["minio server /data --console-address :9090"]
        volumeMounts:
        - mountPath: /data
          name: minio-data
      volumes:
      - name: minio-data
        hostPath:
          path: /data/minio  # Chevalocal dans Minikube
          type: DirectoryOrCreate